version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./server/php
    container_name: php
    volumes:
      - .:/var/www
    depends_on:
      - redis
    # user: "${UID:-1000}:${GID:-1000}"  # uncomment if needed for permissions

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
