### List all users
GET {{baseURL}}/api/user

### List user by ID
GET {{baseURL}}/api/user/8

### Register new user
POST {{baseURL}}/api/user
Content-Type: application/json

{
    "name": "Kakashi",
    "email": "ninja@sacana.com",
    "password": "alguémnéh"
}

### Update user
PUT {{baseURL}}/api/user/8
Content-Type: application/json

{
    "email": "ninja@sempai.com"
}

### Delete user
DELETE {{baseURL}}/api/user/7