@baseURL = http://localhost:8080

### Register new user
POST {{baseURL}}/api/register
Content-Type: application/json

{
    "name": "Jakie Chan",
    "email": "jakie@chan.com",
    "password": "karatekid"
}